Hệ Mã Hill

Mã Hoá Hill

In [1]:
import numpy as np

In [2]:
K = np.array([[1, 2 ,3],[0, 1, 4],[0, 0, -1]])
# print(np.linalg.inv(A))
P = "paymoremoney"
# print(P)
def mahoa_hill(K,P):
  Z_26 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  P = P.upper()
  m = len(K)
  PP = []
  PP.append([])
  count = 0;
  d = 0
  for i in range(0,len(P)):
    for j in range(0,len(Z_26)):
      if(P[i] == Z_26[j]):
        PP[d].append(j)
    count = count + 1
    if(count == 3 and i < len(P)-1):
      PP.append([])
      d = d + 1
      count = 0 
  # print(PP)

  C = []
  for i in range(0,len(PP)):
    P_array = []
    P_array.append([])
    P_array[0].extend(PP[i])
    P_array = np.array(P_array)
    P_array = P_array.T
     
    C.append(((K.dot(P_array))%26).T)
  CC = []
  for i in range(0,len(C)):
    CC.append([])
    for j in range(0,len(C[i])):
      CC[i].extend(C[i][j])
  # print(CC)
  for i in range(0,len(CC)):
    for j in range(0,len(CC[i])):
      for k in range(0,len(Z_26)):
        if(CC[i][j] == k):
          CC[i][j] = Z_26[k]
  return CC 
 
mahoa_hill(K,P)

[['J', 'S', 'C'], ['N', 'E', 'J'], ['S', 'Q', 'M'], ['P', 'W', 'C']]

Giải MÃ Hill

In [3]:
def detMaTran(A):
 
  det = 0
  if(len(A)==2):
    
    det = A[0][0]*A[1][1] - A[0][1]*A[1][0]
    
  else:
    
    pp_A = []
    for i in range(0,1):
      for j in range(0,len(A[i])):
        pp_A = []
        d = 0
        for m in range(1,len(A)):
          if(m != 0):
            pp_A.append([])

            for n in range(0,len(A[m])):

              if(n != j):
                pp_A[d].append(A[m][n])   
                
                
            d = d + 1
        detpp_A = detMaTran(pp_A)
        det += detpp_A * A[i][j] * ((-1)**(i+j))

  return det

# K = np.array([[1, 2 ,3],[0, 1, 4],[0, 0, -1]])
# detMaTran(K)

In [4]:
def MaTranNghichDao(A):
   
  detA = detMaTran(A)
  PA  = []
  p_A = []
  for i in range(0,len(A)):
    p_A.append([])
    for j in range(0,len(A)):
      p_A[i].append("0")

  for i in range(0,len(A)):
    for j in range(0,len(A)):
      pp_A = []
      d = 0
      for m in range(0,len(A)):
        
        if(m != i):   
          pp_A.append([])
        
          for n in range(0,len(A)):
            
            if(n != j):
              
              # charm = str(m)
              # charn = str(n)
              # charA = str(A[m][n])
              # print("A[" +charm+ "]" + "[" +charn+ "] = " + charA)
              pp_A[d].append((A[m][n]))
            
          d = d + 1
       
      detppp_A = 0
      detppp_A = detMaTran(pp_A)
      detppp_A = ((detppp_A * (-1)**(i+j))/detA)
      # detppp_A = int(detppp_A * detA)
      
     
      p_A[i][j] = detppp_A

      PA = np.array(p_A)
      
      PA = PA.T
     
      # print(PA)
      # print(pp_A)
      # print(detppp_A)
      
      
  return PA
      
MaTranNghichDao(K)
print(K.dot(MaTranNghichDao(K)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
C = mahoa_hill(K,P)
def giaima_hill(K,C):
  
  Z_26 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  ZZ_26 = []
  for i in range(0,len(Z_26)):
    ZZ_26.append(Z_26[i])
  K_1 = MaTranNghichDao(K)
  # print(K_1)
  CC = []
  for i in range(0,len(C)):
    CC.extend(C[i])
  # print(CC)

  for i in range(0,len(CC)):
    for m in range(0,len(ZZ_26)):
      if(CC[i] == ZZ_26[m]):
        CC[i] = m
  # print(CC)
  CCC = []
  CCC.append([])
  count = 0
  d = 0
  for i in range(0,len(CC)):  
    CCC[d].append(CC[i])
    count = count + 1
    if(count == len(K) and i < len(CC) -1 ):
      CCC.append([])
      d = d + 1
      count = 0
  # print(CCC)
  B = []
  for i in range(0,len(CCC)):
    CCC_array = []
    CCC_array.append([])
    CCC_array[0].extend(CCC[i])
    CCC_array = np.array(CCC_array)
    CCC_array = CCC_array.T
    
    B.append(((K_1.dot(CCC_array))%26).T)
  # print(B)
  BB = []
  for i in range(0,len(B)):
    BB.append([])
    for j in range(0,len(B[i])):
      BB[i].extend(B[i][j])
  # print(BB)
  chuoiBB = ""
  for i in range(0,len(BB)):
    for j in range(0,len(BB[i])):
      for k in range(0,len(Z_26)):
        if(BB[i][j] == k):
          BB[i][j] = Z_26[k]
          chuoiBB += Z_26[k]
  chuoiBB = chuoiBB.lower()
  
  
  return chuoiBB

giaima_hill(K,C)

'paymoremoney'