MÃ Hóa Caesar

In [ ]:
def encrypt(plaintext, k):
    result = ""
    #duyệt chuỗichuỗi
    for i in range(len(plaintext)):
        char = plaintext[i]
         #mã hóa các ký tự viết hoa
        if(char.isupper()):
            result += chr((ord(char) + k-65) % 26 +65)
        #mã hóa các ký tự viết thường
        else:
            result += chr((ord(char) + k - 97) % 26 + 97)
    return result

In [ ]:
plaintext = "wemeettomorrow"
k =12
ciphertext = encrypt(plaintext,k);
print("Ciphertext: " + ciphertext );

Ciphertext: iqyqqffayaddai


GIẢI MÃ Caesar

In [ ]:
def decrypt(ciphertext,k):
    result = ""

    for i in range(len(ciphertext)):
        char = ciphertext[i]
          # giải mã các ký tự viết hoa
        if(char.isupper()):
            result += chr((ord(char) - k-65) % 26 +65)
      # giải mã các ký tự viết thường
        else:
            result += chr((ord(char) - k - 97) % 26 + 97)
    return result

k=12
print("Plaintext: " + decrypt(ciphertext,k));

Plaintext: wemeettomorrow


Tấn Công Hệ mã Caesar

In [ ]:
ciphertext = input('Type ciphertext:')
for k in range(0,26):
    plaintext = decrypt(ciphertext,k)
    print("For key = ", k, "plaintext="+plaintext.lower())
#K=24 welcometophenikaa

Type ciphertext:tomoruiyghjk
For key =  0 plaintext=tomoruiyghjk
For key =  1 plaintext=snlnqthxfgij
For key =  2 plaintext=rmkmpsgwefhi
For key =  3 plaintext=qljlorfvdegh
For key =  4 plaintext=pkiknqeucdfg
For key =  5 plaintext=ojhjmpdtbcef
For key =  6 plaintext=nigilocsabde
For key =  7 plaintext=mhfhknbrzacd
For key =  8 plaintext=lgegjmaqyzbc
For key =  9 plaintext=kfdfilzpxyab
For key =  10 plaintext=jecehkyowxza
For key =  11 plaintext=idbdgjxnvwyz
For key =  12 plaintext=hcacfiwmuvxy
For key =  13 plaintext=gbzbehvltuwx
For key =  14 plaintext=fayadgukstvw
For key =  15 plaintext=ezxzcftjrsuv
For key =  16 plaintext=dywybesiqrtu
For key =  17 plaintext=cxvxadrhpqst
For key =  18 plaintext=bwuwzcqgoprs
For key =  19 plaintext=avtvybpfnoqr
For key =  20 plaintext=zusuxaoemnpq
For key =  21 plaintext=ytrtwzndlmop
For key =  22 plaintext=xsqsvymcklno
For key =  23 plaintext=wrpruxlbjkmn
For key =  24 plaintext=vqoqtwkaijlm
For key =  25 plaintext=upnpsvjzhikl


HỆ MÃ Playfair

mã hóa playfai

In [ ]:

playtext = "HELLOONEANDALL"
K = "THEDIEIS";
def mahoa_playfair(K,playtext):
  #LỌC RA CÁC KÝ TỰ KHÁC NHAU TRONG KHOÁ(k)
  k_mang = [];
  k_mang.append(K[0])
  i=1
  for x in range(1,len(K)):
    g = 0;
    d = 0;
    if(K[x]=='I' or K[x]=='J'):
      g = 1;
    for y in range(0,x):
      _XY = 0;
      if(K[y]=='I' or K[y]=='J'):
        _XY = 1;
      if(g == 1):
        if(_XY == 1):
          d=1
      else:
        if(K[x]==K[y]):
          d=1;

    if(d==0):
      k_mang.append(K[x])
    
  # print(k_mang);
  ky_tu = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  _ky_tu = []
  for i in range(0,len(ky_tu)):
    _IJ=0
    if(ky_tu[i]=='I' or ky_tu[i]=='J'):
      _IJ=1
    d = 0;
    for j in range(0,len(k_mang)):
      IJ=0
      if(k_mang[j]=='I' or k_mang[j]=='J'):
          IJ = 1
      if(_IJ == 1):
        if(IJ==1):
          d=1
          i = i + 1;
      else:
        if(ky_tu[i]==k_mang[j]):
          d=1;
  
    if(d==0):
      _ky_tu.append(ky_tu[i])
  # print(_ky_tu)
  Ma_Tran = []
  for i in range(0,5):
    Ma_Tran.append([])
  
  count = len(k_mang)
  _j = 0;
  m = 0;
  n = 0;
  for i in range(0,len(Ma_Tran)):
    if(count > 0):
      for j in range(0,5):
        if(count > 0):
          Ma_Tran[i].append(k_mang[_j])
          count = count - 1
          _j = _j + 1
          
          n = j
          m = i
  # print(Ma_Tran)
  # print(m)
  # print(n)
  if( n == 4):
    m = m + 1
    n = 0
  else:
    n = n + 1
  p = len(_ky_tu)
  _p = 0
  for i in range(m,len(Ma_Tran)):
    if(p > 0):
      for j in range(n,5):
        if(p > 0):
          Ma_Tran[i].append(_ky_tu[_p])
          p = p - 1
          _p = _p + 1
      n = 0    
  # print(Ma_Tran)

  _playtext = []
  _playtext.extend(playtext)
  #print(_playtext)
  __playtext = []
  count = len(_playtext)
  ii = 0
  while(ii < count - 1 ):
    if(_playtext[ii] == _playtext[ii + 1]):
      __playtext.append([_playtext[ii],'X'])
    else:
      if(_playtext[ii] != _playtext[ii + 1]):
        __playtext.append([_playtext[ii],_playtext[ii + 1]])
        ii = ii + 1;
    
    ii = ii + 1
    if(count - ii == 1):
      __playtext.append([_playtext[ii],'X'])


  # print(__playtext)
  C = []
  mm_0 = 0
  nn_0 = 0
  mm_1 = 0
  nn_1 = 0
  d0 = 0
  d1 = 0
  for i in range(0,len(__playtext)):
    for m in range(0,len(Ma_Tran)):
      for n in range(0,len(Ma_Tran[m])):
        if(__playtext[i][0] == Ma_Tran[m][n]):
          mm_0 = m
          nn_0 = n
          d0 = 1
        if(__playtext[i][1] == Ma_Tran[m][n]):
          mm_1 = m
          nn_1 = n
          d1 = 1
        if(d0 == 1 and d1 == 1):
          d0 = 0
          d1 = 0
          if(mm_0 == mm_1):
            if(nn_0 == 4 or nn_1 == 4):
              if(nn_0 == 4):
                nn_0 = 0
                C.append([Ma_Tran[mm_0][nn_0],Ma_Tran[mm_1][nn_1 + 1]])
              else:
                nn_1 = 0
                C.append([Ma_Tran[mm_0][nn_0 + 1],Ma_Tran[mm_1][nn_1]])
              
            else:
              C.append([Ma_Tran[mm_0][nn_0 + 1],Ma_Tran[mm_1][nn_1 + 1]])
          elif(nn_0 == nn_1):
            if(mm_0 == 4 or mm_1 == 4):
              if(mm_0 == 4):
                mm_0 = 0
                C.append([Ma_Tran[mm_0][nn_0],Ma_Tran[mm_1 + 1][nn_1]])
              else:
                mm_1 = 0
                C.append([Ma_Tran[mm_0 + 1][nn_0],Ma_Tran[mm_1][nn_1]])
              
            else:
              C.append([Ma_Tran[mm_0 + 1][nn_0],Ma_Tran[mm_1 + 1][nn_1]])
          else:
            C.append([Ma_Tran[mm_0][nn_1],Ma_Tran[mm_1][nn_0]])

  return C       
  
mahoa_playfair(K,playtext)

[['E', 'D'],
 ['Q', 'E'],
 ['G', 'Q'],
 ['U', 'G'],
 ['H', 'B'],
 ['M', 'I'],
 ['B', 'K'],
 ['Q', 'E']]

Giải Mã playfair

In [ ]:
CC = []
CC = (mahoa_playfair(K,playtext))
def giaima_playfair(K, CC):
  k_mang = [];
  k_mang.append(K[0])
  i=1
  for x in range(1,len(K)):
    g = 0;
    d = 0;
    if(K[x]=='I' or K[x]=='J'):
      g = 1;
    for y in range(0,x):
      _XY = 0;
      if(K[y]=='I' or K[y]=='J'):
        _XY = 1;
      if(g == 1):
        if(_XY == 1):
          d=1
      else:
        if(K[x]==K[y]):
          d=1;

    if(d==0):
      k_mang.append(K[x])
    
  # print(k_mang);
  ky_tu = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  _ky_tu = []
  for i in range(0,len(ky_tu)):
    _IJ=0
    if(ky_tu[i]=='I' or ky_tu[i]=='J'):
      _IJ=1
    d = 0;
    for j in range(0,len(k_mang)):
      IJ=0
      if(k_mang[j]=='I' or k_mang[j]=='J'):
          IJ = 1
      if(_IJ == 1):
        if(IJ==1):
          d=1
          i = i + 1;
      else:
        if(ky_tu[i]==k_mang[j]):
          d=1;
  
    if(d==0):
      _ky_tu.append(ky_tu[i])
  # print(_ky_tu)
  Ma_Tran = []
  for i in range(0,5):
    Ma_Tran.append([])
  
  count = len(k_mang)
  _j = 0;
  m = 0;
  n = 0;
  for i in range(0,len(Ma_Tran)):
    if(count > 0):
      for j in range(0,5):
        if(count > 0):
          Ma_Tran[i].append(k_mang[_j])
          count = count - 1
          _j = _j + 1
          
          n = j
          m = i
  # print(Ma_Tran)
  # print(m)
  # print(n)
  if( n == 4):
    m = m + 1
    n = 0
  else:
    n = n + 1
  p = len(_ky_tu)
  _p = 0
  for i in range(m,len(Ma_Tran)):
    if(p > 0):
      for j in range(n,5):
        if(p > 0):
          Ma_Tran[i].append(_ky_tu[_p])
          p = p - 1
          _p = _p + 1
      n = 0
  # print(Ma_Tran)
  P = []
  mm_0 = 0
  nn_0 = 0
  mm_1 = 0
  nn_1 = 0
  d0 = 0
  d1 = 0
  for i in range(0,len(CC)):
    for m in range(0,len(Ma_Tran)):
      for n in range(0,len(Ma_Tran[m])):
        if(CC[i][0] == Ma_Tran[m][n]):
          mm_0 = m
          nn_0 = n
          d0 = 1
        if(CC[i][1] == Ma_Tran[m][n]):
          mm_1 = m
          nn_1 = n
          d1 = 1
        if(d0 == 1 and d1 == 1):
          d0 = 0
          d1 = 0
          if(mm_0 == mm_1):
            if(nn_0 == 0 or nn_1 == 0):
              if(nn_0 == 0):
                nn_0 = 4
                P.append([Ma_Tran[mm_0][nn_0],Ma_Tran[mm_1][nn_1 - 1]])
              else:
                nn_1 = 4
                P.append([Ma_Tran[mm_0][nn_0 - 1],Ma_Tran[mm_1][nn_1]])
              
            else:
              P.append([Ma_Tran[mm_0][nn_0 - 1],Ma_Tran[mm_1][nn_1 - 1]])
          elif(nn_0 == nn_1):
            if(mm_0 == 0 or mm_1 == 0):
              if(mm_0 == 0):
                mm_0 = 4
                P.append([Ma_Tran[mm_0][nn_0],Ma_Tran[mm_1 - 1][nn_1]])
              else:
                mm_1 = 4
                P.append([Ma_Tran[mm_0 - 1][nn_0],Ma_Tran[mm_1][nn_1]])
              
            else:
              P.append([Ma_Tran[mm_0 - 1][nn_0],Ma_Tran[mm_1 - 1][nn_1]])
          else:
            P.append([Ma_Tran[mm_0][nn_1],Ma_Tran[mm_1][nn_0]])
  PP = ""

  for i in range(0,len(P)):
    for j in range(0,len(P[i])):
      if(P[i][j] != 'X'):
        PP += chr(ord(P[i][j]))

  return PP
giaima_playfair(K,CC)

[['T', 'H', 'E', 'D', 'I'], ['S', 'A', 'B', 'C', 'F'], ['G', 'K', 'L', 'M', 'N'], ['O', 'P', 'Q', 'R', 'U'], ['V', 'W', 'X', 'Y', 'Z']]


'HELLOONEANDALL'

Hệ Mã Hill

Mã Hoá Hill

In [ ]:
import numpy as np

In [425]:
K = np.array([[1, 2 ,3],[0, 1, 4],[0, 0, -1]])
# print(np.linalg.inv(A))
P = "paymoremoney"
# print(P)
def mahoa_hill(K,P):
  Z_26 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  P = P.upper()
  m = len(K)
  PP = []
  PP.append([])
  count = 0;
  d = 0
  for i in range(0,len(P)):
    for j in range(0,len(Z_26)):
      if(P[i] == Z_26[j]):
        PP[d].append(j)
    count = count + 1
    if(count == 3 and i < len(P)-1):
      PP.append([])
      d = d + 1
      count = 0 
  # print(PP)

  C = []
  for i in range(0,len(PP)):
    P_array = []
    P_array.append([])
    P_array[0].extend(PP[i])
    P_array = np.array(P_array)
    P_array = P_array.T
     
    C.append(((K.dot(P_array))%26).T)
  CC = []
  for i in range(0,len(C)):
    CC.append([])
    for j in range(0,len(C[i])):
      CC[i].extend(C[i][j])
  # print(CC)
  for i in range(0,len(CC)):
    for j in range(0,len(CC[i])):
      for k in range(0,len(Z_26)):
        if(CC[i][j] == k):
          CC[i][j] = Z_26[k]
  return CC 
 
mahoa_hill(K,P)

[['J', 'S', 'C'], ['N', 'E', 'J'], ['S', 'Q', 'M'], ['P', 'W', 'C']]

Giải MÃ Hill

In [426]:
import numpy as np
def detMaTran(A):
 
  det = 0
  if(len(A)==2):
    
    det = A[0][0]*A[1][1] - A[0][1]*A[1][0]
    
  else:
    
    pp_A = []
    for i in range(0,1):
      for j in range(0,len(A[i])):
        pp_A = []
        d = 0
        for m in range(1,len(A)):
          if(m != 0):
            pp_A.append([])

            for n in range(0,len(A[m])):

              if(n != j):
                pp_A[d].append(A[m][n])   
                
                
            d = d + 1
        detpp_A = detMaTran(pp_A)
        det += detpp_A * A[i][j] * ((-1)**(i+j))

  return det

# K = np.array([[1, 2 ,3],[0, 1, 4],[0, 0, -1]])
# detMaTran(K)

In [427]:

import numpy as np

def MaTranNghichDao(A):
   
  detA = detMaTran(A)
  PA  = []
  p_A = []
  for i in range(0,len(A)):
    p_A.append([])
    for j in range(0,len(A)):
      p_A[i].append("0")

  for i in range(0,len(A)):
    for j in range(0,len(A)):
      pp_A = []
      d = 0
      for m in range(0,len(A)):
        
        if(m != i):   
          pp_A.append([])
        
          for n in range(0,len(A)):
            
            if(n != j):
              
              # charm = str(m)
              # charn = str(n)
              # charA = str(A[m][n])
              # print("A[" +charm+ "]" + "[" +charn+ "] = " + charA)
              pp_A[d].append((A[m][n]))
            
          d = d + 1
       
      detppp_A = 0
      detppp_A = detMaTran(pp_A)
      detppp_A = ((detppp_A * (-1)**(i+j))/detA)
      # detppp_A = int(detppp_A * detA)
      
     
      p_A[i][j] = detppp_A

      PA = np.array(p_A)
      
      PA = PA.T
     
      # print(PA)
      # print(pp_A)
      # print(detppp_A)
      
      
  return PA
      
MaTranNghichDao(K)
print(K.dot(MaTranNghichDao(K)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [428]:
C = mahoa_hill(K,P)

print(C)

[['J', 'S', 'C'], ['N', 'E', 'J'], ['S', 'Q', 'M'], ['P', 'W', 'C']]


In [435]:
import numpy as np
C = mahoa_hill(K,P)

def giaima_hill(K,C):
  
  Z_26 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  ZZ_26 = []
  for i in range(0,len(Z_26)):
    ZZ_26.append(Z_26[i])
  K_1 = MaTranNghichDao(K)
  # print(K_1)
  CC = []
  for i in range(0,len(C)):
    CC.extend(C[i])
  # print(CC)

  for i in range(0,len(CC)):
    for m in range(0,len(ZZ_26)):
      if(CC[i] == ZZ_26[m]):
        CC[i] = m
  # print(CC)
  CCC = []
  CCC.append([])
  count = 0
  d = 0
  for i in range(0,len(CC)):  
    CCC[d].append(CC[i])
    count = count + 1
    if(count == len(K) and i < len(CC) -1 ):
      CCC.append([])
      d = d + 1
      count = 0
  # print(CCC)
  B = []
  for i in range(0,len(CCC)):
    CCC_array = []
    CCC_array.append([])
    CCC_array[0].extend(CCC[i])
    CCC_array = np.array(CCC_array)
    CCC_array = CCC_array.T
    
    B.append(((K_1.dot(CCC_array))%26).T)
  # print(B)
  BB = []
  for i in range(0,len(B)):
    BB.append([])
    for j in range(0,len(B[i])):
      BB[i].extend(B[i][j])
  # print(BB)
  chuoiBB = ""
  for i in range(0,len(BB)):
    for j in range(0,len(BB[i])):
      for k in range(0,len(Z_26)):
        if(BB[i][j] == k):
          BB[i][j] = Z_26[k]
          chuoiBB += Z_26[k]
  chuoiBB = chuoiBB.lower()
  
  
  return chuoiBB

giaima_hill(K,C)

'paymoremoney'

hệ mã vigenere

mã hoá vigenere

In [479]:
K = "deceptive"
P = "wearediscoveredsaveyourself"
def mahoa_vigenere(K,P):
  if(len(K) < len(P)):
    Z_26 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
   
    KK = K.upper()
    P = P.upper()
    count = len(P) - len(K)
    count_k = 0
    for i in range(0,count):
      if(count_k == len(K)):
        count_k = 0
      KK += KK[count_k]
      count_k = count_k + 1
    
    C = ""
    for i in range(0,len(P)):
      index = (ord(KK[i]) + ord(P[i]))%26
      for j in range(0,len(Z_26)):
        if(index == j):
          C += Z_26[j]
    
    return C
 
mahoa_vigenere(K,P)

'ZICVTWQNGRZGVTWAVZHCQYGLMGJ'

GIẢI MÃ VIGENERE

In [481]:

C = mahoa_vigenere(K,P)
print(C)
print(len(C))

ZICVTWQNGRZGVTWAVZHCQYGLMGJ
27


In [533]:
def giaima_vigenere(K,C):
  if(len(K) < len(C)):
    Z_26 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    
    KK = K.upper()
    count = len(C) - len(K)
    count_k = 0
    for i in range(0,count):
      if(count_k == len(K)):
        count_k = 0
      KK += KK[count_k]
      count_k = count_k + 1
    
    P = ""
    # print(KK)
    # print(C)
    for i in range(0,len(C)):
      index = (ord(C[i]) - ord(KK[i]))%26
      for j in range(0,len(Z_26)):
        if(index == j):
          P += Z_26[j]
    P = P.lower()
    return P
giaima_vigenere(K,C)

DECEPTIVEDECEPTIVEDECEPTIVE
ZICVTWQNGRZGVTWAVZHCQYGLMGJ


'wearediscoveredsaveyourself'

In [535]:
print(ord('Z'))
print(ord('D'))
print(22%26)

90
68
22


In [ ]:
m = int(input())
n = int(input())
mt=[]
def NhapMaTran():
    for i in range(0,m):
        mt.append([])
        print(mt)
        for j in range(0,n):
            print ("Phan tu hang",i,"cot",j)
            pt=int(input())
            mt[i].append(pt)
NhapMaTran()
A = np.array(mt)

print(A)
print(mt)
print(A - A)

2
2
[[]]
Phan tu hang 0 cot 0
1
Phan tu hang 0 cot 1
2
[[1, 2], []]
Phan tu hang 1 cot 0
3
Phan tu hang 1 cot 1
4
[[1 2]
 [3 4]]
[[1, 2], [3, 4]]
[[0 0]
 [0 0]]
